config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :items

  resources :electees

  resources :users

  resources :line_items

  resources :carts

  resources :products

  get 'login'=>"sessions#new", as: :login

  post 'login'=>"sessions#create"

  patch 'logout'=>"sessions#destroy", as: :logout

   root 'products#index'

end

app/models/electee.rb
class Electee < ActiveRecord::Base
  belongs_to :user
  has_many :items
  
  def add_item_electee(p)
    item = items.where(product_id: p.id).first
    unless item
      item = self.items.build(product: p, price: p.price)
    end
    item.save
  end
end

app/controllers/electees_controller.rb
class ElecteesController < ApplicationController
  before_action :set_electee, only: [:show, :edit, :update, :destroy]

  # GET /electees
  # GET /electees.json
  def index
    @electees = Electee.all
  end

  # GET /electees/1
  # GET /electees/1.json
  def show
  end

  # GET /electees/new
  def new
    @electee = Electee.new
  end

  # GET /electees/1/edit
  def edit
  end

  # POST /electees
  # POST /electees.json
  def create
    @electee = Electee.new(electee_params)

    respond_to do |format|
      if @electee.save
        format.html { redirect_to @electee, notice: 'Electee was successfully created.' }
        format.json { render :show, status: :created, location: @electee }
      else
        format.html { render :new }
        format.json { render json: @electee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /electees/1
  # PATCH/PUT /electees/1.json
  def update
    respond_to do |format|
      if @electee.update(electee_params)
        format.html { redirect_to @electee, notice: 'Electee was successfully updated.' }
        format.json { render :show, status: :ok, location: @electee }
      else
        format.html { render :edit }
        format.json { render json: @electee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electees/1
  # DELETE /electees/1.json
  def destroy
    @electee.destroy
    respond_to do |format|
      format.html { redirect_to electees_url, notice: 'Electee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_electee
      @electee = Electee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def electee_params
      params.require(:electee).permit(:user_id)
    end
end

app/helpers/electees_helper.rb
module ElecteesHelper
end

app/views/electees/_form.html.haml
= form_for @electee do |f|
  - if @electee.errors.any?
    #error_explanation
      %h2= "#{pluralize(@electee.errors.count, "error")} prohibited this electee from being saved:"
      %ul
        - @electee.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/electees/edit.html.haml
%h1 Editing electee

= render 'form'

= link_to 'Show', @electee
\|
= link_to 'Back', electees_path

app/views/electees/index.html.haml
%h1 Listing electees

%table
  %thead
    %tr
      %th User
      %th
      %th
      %th
      
  %tbody
    - @electees.each do |electee|
      %tr
        %td= electee.user
        %td= link_to 'Show', electee
        %td= link_to 'Edit', edit_electee_path(electee)
        %td= link_to 'Destroy', electee, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Electee', new_electee_path

app/views/electees/new.html.haml
%h1 New electee

= render 'form'

= link_to 'Back', electees_path

app/views/electees/show.html.haml
%p#notice= notice
.page-header
  .fa.fa-shopping-cart.fa-4x.li
    Ваше избранное

.row
  .col-md-3
    .list-group
      .list-group-item.active
        .fa.fa-pencil.li
          Название
      .list-group-item
        .fa.fa-info-circle.li
          Описание
      .list-group-item
        .fa.fa-ruble.li
          Цена
      .list-group-item
        .fa.fa-download.li
          Вес

.row
  - @electee.items.each do |item|
    .col-md-3
      .list-group
        .list-group-item.active
          .fa.fa-pencil.li
            #{item.product.name}
        .list-group-item
          .fa.fa-info-circle.li
            #{item.product.description}
        .list-group-item
          .fa.fa-ruble.li
            #{number_to_currency(item.price, separator: ",", delimiter: "", format: "%n")}
        .list-group-item
          .fa.fa-download.li
            #{number_to_human(item.product.weight, units: {unit: "г", thousand: "кг"})}
        .list-group-item
          .fa.fa-remove.li
            =link_to 'Удалить', item, method: :delete, data: {:confirm => 'Вы уверены?'}

= link_to 'Очистить избранное', @electee, data:{method: :delete, confirm: "Вы уверены?"}, class: "btn btn-primary"
\|
= link_to 'Вернуться к выбору товаров', products_path, class: "btn btn-info"