config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :items

  resources :electees

  resources :users

  resources :line_items

  resources :carts

  resources :products

  get 'login'=>"sessions#new", as: :login

  post 'login'=>"sessions#create"

  patch 'logout'=>"sessions#destroy", as: :logout

   root 'products#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  validates :product, presence: true
  validates :product_id, uniqueness: {scope: :cart_id}
  validates :cart, presence: true
  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validates :price, presence: true

  def total_price
    quantity*price
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  #include CurrentCart

  #before_action :set_cart, only: [:create, :destroy]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = @cart.line_items.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @product = Product.find(params[:product_id])
    @cart.add_item(@product)
    redirect_to @product, notice: 'Товар добавлен в корзину.'
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    if @line_item.update(line_item_params)
      redirect_to @line_item, notice: 'Элемент успешно изменён.'
    else
      render :edit
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    if @line_item.quantity == 1
      @line_item.destroy
    else
      @line_item.quantity -= 1
      @line_item.save
    end
    redirect_to @cart, notice: 'Элемент успешно удалён.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:quantity, :price, :cart_id, :product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  - if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :cart
    = f.text_field :cart
  .field
    = f.label :product
    = f.text_field :product
  .actions
    = f.submit 'Сохранить'

app/views/line_items/edit.html.haml
%h1 Редактирование элемента

= render 'form'

= link_to 'Показать', @line_item
\|
= link_to 'Назад', line_items_path

app/views/line_items/index.html.haml
.page-header
  %h1 Корзина
-if @line_items.blank?
  .alert.alert-info В корзине нет товаров
-else
  .list-group
    -@line_items.each_with_index do |line_item, i|
      .list-group-item
        .pull-right
          =line_item.quantity
          &times;
          =number_to_currency(line_item.price)
          ="= #{number_to_currency(line_item.total_price)}"
          %span.text-danger="#{i+1}"
          =line_item.product.name
        .clearfix
  .alert.alert-info
    Всего
    =@line_items.to_a.sum(&:quantity)
    #{Russian.p(@line_items.to_a.sum(&:quantity),'товар','товара','товаров')} на сумму
    =number_to_currency @line_items.to_a.sum(&:total_price)
%table
  %thead
    %tr
      %th Количество
      %th Цена
      %th Корзина
      %th Товар
      %th
      %th
      %th
      
  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.quantity
        %td= line_item.price
        %td= line_item.cart
        %td= line_item.product
        %td= link_to 'Показать', line_item
        %td= link_to 'Редактировать', edit_line_item_path(line_item)
        %td= link_to 'Удалить', line_item, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br

= link_to 'Новый элемент', new_line_item_path
= link_to 'Очистить корзину', @cart, data:{method: :delete, confirm: 'Вы уверены?'}

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Количество:
  = @line_item.quantity
%p
  %b Цена:
  = @line_item.price
%p
  %b Корзина:
  = @line_item.cart
%p
  %b Товар:
  = @line_item.product

= link_to 'Редактировать', edit_line_item_path(@line_item)
\|
= link_to 'Назад', line_items_path